// Mocks generated by Mockito 5.4.5 from annotations
// in tasklist/test/task_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:tasklist/task_manager.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskManager extends _i1.Mock implements _i2.TaskManager {
  MockTaskManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get tasks =>
      (super.noSuchMethod(Invocation.getter(#tasks), returnValue: <String>[])
          as List<String>);

  @override
  set tasks(List<String>? _tasks) => super.noSuchMethod(
    Invocation.setter(#tasks, _tasks),
    returnValueForMissingStub: null,
  );

  @override
  List<String> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: <String>[],
          )
          as List<String>);
}
