// Mocks generated by Mockito 5.4.5 from annotations
// in tasklist/test/task_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tasklist/task_list_controller.dart' as _i2;
import 'package:tasklist/task_manager.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskListController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskListController extends _i1.Mock
    implements _i2.TaskListController {
  MockTaskListController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addTask(String? title) => super.noSuchMethod(
    Invocation.method(#addTask, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTask(int? index, String? newTitle) => super.noSuchMethod(
    Invocation.method(#updateTask, [index, newTitle]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTaskCompletion(int? index) => super.noSuchMethod(
    Invocation.method(#toggleTaskCompletion, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTask(int? index) => super.noSuchMethod(
    Invocation.method(#deleteTask, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderTasks(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderTasks, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskManager extends _i1.Mock implements _i4.TaskManager {
  MockTaskManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  void addTask(String? title) => super.noSuchMethod(
    Invocation.method(#addTask, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTaskTitle(int? index, String? newTitle) => super.noSuchMethod(
    Invocation.method(#updateTaskTitle, [index, newTitle]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTaskCompletion(int? index) => super.noSuchMethod(
    Invocation.method(#toggleTaskCompletion, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTask(int? index) => super.noSuchMethod(
    Invocation.method(#deleteTask, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderTasks(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderTasks, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );
}
